const bcTypes = {
    CREATE_BC_START: 'CREATE_BC_START',
    JOIN_BC_START: 'JOIN_BC_START',
    CREATED_BC_SUCCESS: 'CREATED_BC_SUCCESS',
    FETCH_BC_START: 'FETCH_BC_START',
    SET_BC: 'SET_BC',
    UPDATED_BC_SUCCESS: 'UPDATED_BC_SUCCESS',
    BOOK_IN_BC: 'BOOK_IN_BC',
    CREATE_COMMENT_START: 'CREATE_COMMENT_START',
    CREATED_COMMENT_SUCCESS: 'CREATED_COMMENT_SUCCESS',
    UPDATE_RATING: 'UPDATE_RATING'
    
};

export default bcTypes;